import jood from "../../assets/svg/jood.svg";

const hotels = [
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 1    ,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: true,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 4,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 7.9,
        type: "Delux Three Bedroom Apartment",
        guestReviews: 579
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: true,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    },
    {
        name: "Jood Hotel Apartments",
        location: "Deria, Dubai",
        image: jood,
        mapsLink:"https://maps.app.goo.gl/rcBWo3V5VqfETFEJ6",
        level: 2,
        costPerNight: 23786,
        tax: Math.round(10000*0.025),
        prePayment: true,
        cancelation: false,
        bookWithoutCard: true,
        beach:true,
        hotel: false,
        rating: 5,
        resort: false,
        guestHouse:false,
        sustainability: true,
        fitness: false,
        bars: true,
        mall: false,
        cinema: true,
        spa: true,
        reviews: 6.9,
        type: "Delux Three Bedroom Apartment"
    }
]

export default hotels;